# General settings or global content
site_title: "How can our favorite characters drive a movie’s success over the years ?"
site_description: "Discover the different character tropes in movies across the decades and how they contribute to the success of a movie."

# Section-specific content
Character-subtitle: "The Different Character Tropes"
succesMovie-subtitle: "The Success of the Movie"

# Additional details for sections
#heroVSvillain-intro: |
  #A tale as old as time! Heroes and villains clash in an epic battle
  #of good versus evil, courage versus cunning.
